project:
  type: website

website:
  title: "Dimple"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Talks"
        href: talks.qmd
      - text: "Posts"
        href: posts/
      - text: "Events"
        href: events.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Presentations"
        href: presentations.qmd

format:
  html:
    theme: carto
